#!/usr/bin/env bash
#
# Verifies event-driven rotation via the Doppler webhook listener.
#
# Strategy: run with a deliberately long rotation interval and cache TTL, so
# poll-based rotation cannot fire within the test window. A change is made in the
# backend and a *signed* webhook is POSTed to the plugin. If the secret rotates,
# it can only be because the webhook path (verify signature -> invalidate cache
# -> rotation check) worked.
#
# Backend selection (same as smoke-test-doppler.sh):
#   - DOPPLER_SMOKE_TOKEN set  -> real Doppler (api.doppler.com); values are
#     seeded/rotated via the Doppler REST API.
#   - otherwise                -> local Go mock server (no account needed).
#
# NOTE: the webhook delivery itself is always self-generated by this script (we
# compute the HMAC signature and POST to the plugin). Doppler cannot reach an
# ephemeral CI runner, so real mode only swaps the value backend, not the
# webhook trigger.

set -ex
SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
REPO_ROOT="$(realpath -- "${SCRIPT_DIR}/../..")"

# shellcheck source=smoke-test-helper.sh
source "${SCRIPT_DIR}/smoke-test-helper.sh"

# Backend configuration
export DOPPLER_SMOKE_TOKEN="${DOPPLER_SMOKE_TOKEN:-}"
export DOPPLER_API_URL="${DOPPLER_API_URL:-https://api.doppler.com}"
export DOPPLER_PROJECT="${DOPPLER_PROJECT:-}"
export DOPPLER_CONFIG="${DOPPLER_CONFIG:-}"
export DOPPLER_MOCK_URL="http://127.0.0.1:18080"
export DOPPLER_MOCK_TOKEN="dp.st.smoke-test"

# Webhook listener configuration
WEBHOOK_PORT="8091"
WEBHOOK_PATH="/webhooks/doppler"
WEBHOOK_URL="http://127.0.0.1:${WEBHOOK_PORT}${WEBHOOK_PATH}"
WEBHOOK_SECRET="smoke-webhook-secret"

# Common configuration
STACK_NAME="smoke-doppler-webhook"
SECRET_NAME="smoke_secret"
COMPOSE_FILE="$(mktemp -t smoke-doppler-webhook-compose.XXXXXX.yml)"

# Unique per-run key so concurrent CI runs never stomp each other's secret.
RUN_ID="$(printf '%s_%s' "${GITHUB_RUN_ID:-local}" "${GITHUB_RUN_ATTEMPT:-1}" \
    | tr -cd '[:alnum:]_' | tr '[:lower:]' '[:upper:]')"
SECRET_KEY="SMOKE_WEBHOOK_PASSWORD_${RUN_ID}"
SECRET_VALUE="doppler-webhook-v1-${RUN_ID}"
SECRET_VALUE_ROTATED="doppler-webhook-v2-${RUN_ID}"

MOCK_SERVER_PID=""
EXIT_CODE=0

doppler_init_backend

cleanup() {
    echo -e "${RED}Running Doppler webhook smoke test cleanup...${DEF}"
    remove_stack "${STACK_NAME}"
    docker secret rm "${SECRET_NAME}" 2>/dev/null || true
    doppler_delete_secret "${SECRET_KEY}"
    if [[ -n "${MOCK_SERVER_PID}" ]]; then
        kill "${MOCK_SERVER_PID}" 2>/dev/null || true
        wait "${MOCK_SERVER_PID}" 2>/dev/null || true
    fi
    rm -f "${COMPOSE_FILE}"
    remove_plugin
    exit "${EXIT_CODE}"
}
trap cleanup EXIT

# doppler_signature BODY — HMAC-SHA256 of BODY keyed by WEBHOOK_SECRET.
doppler_signature() {
    printf '%s' "$1" \
        | openssl dgst -sha256 -hmac "${WEBHOOK_SECRET}" -hex \
        | sed 's/^.*= //'
}

info "Doppler webhook smoke test running in '${DOPPLER_MODE}' mode."

write_doppler_compose "${COMPOSE_FILE}" "${SECRET_NAME}" "${SECRET_KEY}"

if [[ "${DOPPLER_MODE}" == "mock" ]]; then
    info "Starting Doppler API mock server..."
    go run "${REPO_ROOT}/scripts/tests/mock-doppler-server" --token "${DOPPLER_MOCK_TOKEN}" &
    MOCK_SERVER_PID=$!

    elapsed=0
    until curl -fsS \
        -H "Authorization: Bearer ${DOPPLER_MOCK_TOKEN}" \
        "${DOPPLER_MOCK_URL}/v3/configs/config/secrets/download?format=json" >/dev/null; do
        sleep 1
        elapsed=$((elapsed + 1))
        [[ "${elapsed}" -lt 15 ]] || die "Doppler mock server did not become ready within 15s."
    done
    success "Doppler mock server is ready."
fi

info "Seeding secret ${SECRET_KEY}..."
doppler_seed_secret "${SECRET_KEY}" "${SECRET_VALUE}"
doppler_wait_readable "${SECRET_VALUE}" 30
success "Secret ${SECRET_KEY} is readable."

info "Building plugin and setting Doppler + webhook config..."
build_plugin

# Long rotation interval + cache TTL so ONLY the webhook can drive rotation
# within the test window.
docker plugin set "${PLUGIN_NAME}" \
    SECRETS_PROVIDER="doppler" \
    DOPPLER_TOKEN="${DOPPLER_PLUGIN_TOKEN}" \
    DOPPLER_API_URL="${DOPPLER_PLUGIN_API_URL}" \
    DOPPLER_PROJECT="${DOPPLER_PROJECT}" \
    DOPPLER_CONFIG="${DOPPLER_CONFIG}" \
    DOPPLER_CACHE_TTL="1h" \
    ENABLE_ROTATION="true" \
    ROTATION_INTERVAL="1h" \
    ENABLE_MONITORING="false" \
    DOPPLER_WEBHOOK_ENABLE="true" \
    DOPPLER_WEBHOOK_PORT="${WEBHOOK_PORT}" \
    DOPPLER_WEBHOOK_PATH="${WEBHOOK_PATH}" \
    DOPPLER_WEBHOOK_SECRET="${WEBHOOK_SECRET}"
success "Plugin configured with Doppler + webhook settings."

info "Enabling plugin..."
enable_plugin

info "Waiting for webhook listener to come up..."
elapsed=0
until curl -fsS -o /dev/null -X POST "${WEBHOOK_URL}" \
    -H "Content-Type: application/json" \
    -H "X-Doppler-Signature: sha256=deadbeef" \
    -d '{}' 2>/dev/null || [[ "$?" -ne 7 ]]; do
    # exit code 7 == connection refused; keep waiting until the port is open
    sleep 1
    elapsed=$((elapsed + 1))
    [[ "${elapsed}" -lt 20 ]] || die "Webhook listener did not open within 20s."
done
success "Webhook listener is reachable."

info "Deploying swarm stack..."
deploy_stack "${COMPOSE_FILE}" "${STACK_NAME}" 60

info "Verifying initial secret value..."
verify_secret "${STACK_NAME}" "app" "${SECRET_NAME}" "${SECRET_VALUE}" 60

info "Rotating secret in backend (${DOPPLER_MODE}, no webhook yet)..."
doppler_seed_secret "${SECRET_KEY}" "${SECRET_VALUE_ROTATED}"
doppler_wait_readable "${SECRET_VALUE_ROTATED}" 30

info "Negative check: an invalid signature must NOT trigger rotation..."
payload='{"type":"config.secrets.update","diff":{"updated":["'"${SECRET_KEY}"'"]}}'
bad_status=$(curl -fsS -o /dev/null -w '%{http_code}' -X POST "${WEBHOOK_URL}" \
    -H "Content-Type: application/json" \
    -H "X-Doppler-Signature: sha256=0000000000000000000000000000000000000000000000000000000000000000" \
    -d "${payload}" || true)
[[ "${bad_status}" == "401" ]] || die "Expected 401 for bad signature, got ${bad_status}."
sleep 8
cid="$(get_running_container_id "${STACK_NAME}" "app")"
current="$(docker exec "${cid}" cat "/run/secrets/${SECRET_NAME}" 2>/dev/null | tr -d '[:space:]' || true)"
if [[ "${current}" != "${SECRET_VALUE}" ]]; then
    die "Secret changed to '${current}' after an invalid webhook — signature check failed."
fi
success "Invalid signature correctly rejected (secret still '${SECRET_VALUE}')."

info "Sending a valid signed webhook to trigger rotation..."
sig="$(doppler_signature "${payload}")"
ok_status=$(curl -fsS -o /dev/null -w '%{http_code}' -X POST "${WEBHOOK_URL}" \
    -H "Content-Type: application/json" \
    -H "X-Doppler-Signature: sha256=${sig}" \
    -d "${payload}")
[[ "${ok_status}" == "200" ]] || die "Expected 200 for valid signature, got ${ok_status}."
success "Signed webhook accepted."

info "Verifying webhook-driven rotation took effect..."
verify_secret "${STACK_NAME}" "app" "${SECRET_NAME}" "${SECRET_VALUE_ROTATED}" 60

success "Doppler webhook smoke test PASSED (${DOPPLER_MODE} mode)"
